### PR TITLE
Port MASTG-TEST-0041: Testing for Debugging Code and Verbose Error Logging (android) (by @guardsquare)

### LINKED ISSUE #3020: MASTG v1->v2 MASTG-TEST-0041: Testing for Debugging Code and Verbose Error Logging (android)
Create a new MASTG v2 test covering for":

- **Title:** Testing for Debugging Code and Verbose Error Logging
- **ID:** MASTG-TEST-0041
- **Link:** https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0041/
- **Platform:** android
- **MASVS v1:** ['MSTG-CODE-4']
- **MASVS v2:** ['MASVS-RESILIENCE-3']

**Follow the [guidelines](https://docs.google.com/document/d/1veyzE4cVTSnIsKB1DOPUSMhjXow_MtJOtgHeo5HVoho/edit?usp=sharing)**

----

**Summary from the offline discussion:**

- The current test [MASTG-TEST-0041](https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0041/) focuses on `StrictMode`, but it's not clearly about "debugging code", it's more about checking if `StrictMode` is enabled in production, which can aid reverse engineering.
- There seems to be some overlap with [MASTG-BEST-0002](https://mas.owasp.org/MASTG/best-practices/MASTG-BEST-0002/) and [MASTG-TEST-0231](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0231/) which handle sensitive data in logs. But the new required test isn’t about **data leakage**, it’s about verbosity and unintended debug output, fitting better under these items (both linked to the theme of impeding comprehension/static analysis):
    - [MASVS-RESILIENCE-3](https://mas.owasp.org/MASVS/controls/MASVS-RESILIENCE-3/)
    - [MASWE-0094](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0094/)
- We may want to split "logging tests" into PII (and go to PRIVACY), verbose logging (RESILIENCE) and the rest (STORAGE)

**Action Plan:**

1. **Split the current test into two separate tests** (consider better names):
   - **Verbose Logging (StrictMode)**  
     Covers the presence of `StrictMode` in production builds.
   - **Verbose Logging (General / Logcat / Crashlogs)**  
     Covers other sources of excessive logging or unintended debug information (e.g., logcat entries, crash logs).

2. **Create two separate PRs** for each test if that makes implementation easier and inlcude the corresponding demos, e.g.:
   - `StrictMode`
   - Verbose log output via logcat 
   - Crash logs

3. Consider opening an issue to "extract the privacy part (PII, etc.)" from MASTG-TEST-0231 and creating a new test (and demo) for it (the current demo [MASTG-DEMO-0006](https://mas.owasp.org/MASTG/demos/android/MASVS-STORAGE/MASTG-DEMO-0006/MASTG-DEMO-0006/) is still good for MASTG-TEST-0231 because it's about "secrets").

### PR DESCRIPTION
**Pull request by titze**
This PR closes #3020

### CODE REVIEW

**Comment by titze** [comment]
I am unsure about the test itself. It was a dynamic test before, so I kept it like this. But it could very well be a static test, or even both... 

The Test IDs are wrong at the moment, I will update them when we are close to merging the PR.

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    }
+
+    private fun enableStrictMode() {
+        StrictMode.setVmPolicy(
+            StrictMode.VmPolicy.Builder()
+                .detectLeakedSqlLiteObjects() // Detect leaked/unclosed SQLite objects
+                .penaltyLog()                 // Log violations
+                .build()
+        )
+    }
```
Comment (cpholguera) [inline demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt:24]: - `detectLeakedSqlLiteObjects()` was not triggering for me on API 34.
- `detectLeakedClosableObjects()` is more general and includes SQLite cursor leaks.

```suggestion
    private fun enableStrictMode() {
        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedClosableObjects() // Detect leaked/unclosed SQLite objects
                .penaltyLog()                 // Log violations
                .build()
        )
    }
```

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import android.content.Context
+import android.database.sqlite.SQLiteDatabase
+import android.os.StrictMode
+
+
+class MastgTest (private val context: Context){
+
+    fun mastgTest(): String {
+        enableStrictMode()
+        triggerSqliteCursorLeak()
```
Comment (cpholguera) [inline demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt:12]: StrictMode detects leaked closable objects only when the GC runs. So if you leak a cursor but GC hasn't run yet, it won't show anything as it was the case for me.

```suggestion
        triggerSqliteCursorLeak()
        
        System.gc() // Force garbage collection to trigger leak detection
```

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:107)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.os.Looper.loopOnce(Looper.java:232)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.os.Looper.loop(Looper.java:317)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:8705)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
+03-25 10:32:13.539  7952  7960 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```
Comment (cpholguera) [inline demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt:39]:
```suggestion
03-26 10:12:01.577  6218  6230 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
```

File: tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+title: Testing if StrictMode is enabled
+id: MASTG-TEST-0X41
+apis: [StrictMode]
+type: [dynamic]
+weakness: MASWE-0094
+---
+
+## Overview
+
+This test verifies if an app enables [StrictMode](../../../0x05i-Testing-Code-Quality-and-Build-Settings/#strictmode) in production.
```
Comment (cpholguera) [inline tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md:12]:
```suggestion
This test checks whether an app enables [`StrictMode`](../../../0x05i-Testing-Code-Quality-and-Build-Settings/#strictmode) in production. While useful for developers to log policy violations such as disk I/O or network operations in production apps, leaving `StrictMode` enabled can expose sensitive implementation details in the logs that could be exploited by attackers.
```

File: tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md [hunk 5]
```diff
@@ -0,0 +1,26 @@
+---
+platform: android
+title: Testing if StrictMode is enabled
```
Comment (cpholguera) [inline tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md:3]: When writing test titles, imagine that they already start with "Testing for/if", but don't add that to the title. With this suggestion, I'm trying to focus on the observable behavior (violation logs) rather than the internal configuration/presence/"enabled" in the code, which we could reserve for the static version of the test.

```suggestion
title: Logging of StrictMode Violations
```

**Review by cpholguera — CHANGES_REQUESTED** [review]

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt (hunk 3 above)
Comment (titze) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt:39]: I think the full stracktrace is more usable here, because it also shows _where_ the issue is. Otherwise, the log message is not that helpful for a reverse engineer.

File: tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md (hunk 4 above)
Comment (titze) [reply tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x41.md:12]: Shouldn't the second part of the paragraph be better in the weakness? I thought once you are in the test, you should already have understood the problem?

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt (hunk 2 above)
Comment (titze) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/MastgTest.kt:12]: Ah, I let it run for a bit and then it showed. Good catch!

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/run.sh [hunk 6]
```diff
@@ -0,0 +1 @@
+adb logcat -s StrictMode
```
[the remark this answers is not in the document]
Comment (titze) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/run.sh:1]: `-d` would not work here, because the steps say you should run this before executing the app.
Since the exact string that is printed by `StrictMode` could easily change, I would not add the grep.

[the remark this answers is not in the document]
Comment (cpholguera) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/run.sh]: I'd agree if we ran this manually, but if we think about automating this in our pipeline, wouldn't it be better to run it some time after the button was clicked? We need to store it in output.txt, so we could try to run it with `-d` until there's content in output.txt. The content will be dumped anyway, there seems to be no need to run it before clicking.

The more we prepare now for the upcoming pipeline automation, the better.

Removing the grep is fine, though.

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt (hunk 3 above)
Comment (cpholguera) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt:39]: Makes sense!

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/run.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (titze) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/run.sh]: But that then means that the script needs to run after you played with the app? Should be fine I think.

File: demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt (hunk 3 above)
Comment (cpholguera) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt:39]: Please add something in the "Evaluation" section of the demo indicating where the issue is located as seen in the output.

Comment (cpholguera) [reply demos/android/MASVS-RESILIENCE/MASTG-DEMO-0x41/output.txt:39]: Updated suggestion, it includes the right package now: `org.owasp.mastestapp` instead of `com.example.strictmode2`

```sh
03-26 11:33:23.415  2340  2407 D StrictMode: 	at org.owasp.mastestapp.MastgTest.triggerSqliteCursorLeak(MastgTest.kt:35)
03-26 11:33:23.415  2340  2407 D StrictMode: 	at org.owasp.mastestapp.MastgTest.mastgTest(MastgTest.kt:12)
03-26 11:33:23.415  2340  2407 D StrictMode: 	at org.owasp.mastestapp.MainActivityKt$MyScreenContent$1$1$1.invoke(MainActivity.kt:117)
03-26 11:33:23.415  2340  2407 D StrictMode: 	at org.owasp.mastestapp.MainActivityKt$MyScreenContent$1$1$1.invoke(MainActivity.kt:115)
```

**Review by cpholguera — APPROVED** [review]

File: tests/android/MASVS-RESILIENCE/MASTG-TEST-0041.md
Comment (cpholguera) [inline tests/android/MASVS-RESILIENCE/MASTG-TEST-0041.md:1]: This was missing but I just added it so we can merge.
